language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run build:chrome
  - npm run build:firefox
  - npm run build:opera
  - npm run build:edge
deploy:
  provider: releases
  api_key:
    secure: tlYT5a2DbfMwQAbciBg7SLmZOOzaziDnCxQJvu1QQJE2LrxsM86qV4NqmP+ZHhN0cjP0VcGD04oePB9k6ZZcrjg8u7TIGQDiZ0FLG0/TNYbFE+S3DDJyYBXT2LaPToE4pl/3lcoQvngVYAuRr6SovGqZZXyT8PjEbr96+GkZymS0nQQYPc4ZRSwUqseAN92yTygDRcMDXYjEndM8Kgq3wCYeAwSmbwGJZIiiHf5iZIDOe2YWyCwkcbzavXKmRicAuRR3nhi7aY0enLiePoVM4JYOmasOPW2kx1fkGuAzrj5asjkrxAiNII6sXudaytFUNKMljo2s/oY5s98br2hTHmiFHRweiKCnawtN4zkiH5eH8dZ5kze/xVVL2PlykDt2IJJBbtCOE+ldPJ8N1uL/cVnWuRF8gAczjTH3Zmvm/ShKZO5xoL5/qh1J1KvLPRcUXlOfWsv8lYppC8NvnYfz5T28NOgmjq5gPsgj8cB4jJrnfIh1VcvDCo7IugZgPL0TA1Iuu4+q37nyXQBIgDhw3ZmJnumOQ/ZfbZ0vdgxHXeyw0Hzrp5gunDfo3SXl90lEEyD7lH1GFbegEy/5F8oG5XHNs5Bj9nvPRMBcTJYwa3BAHpsAo3I+vHfA1hf05lPR43lJAb3fJG+QXbyY3c01dckgIR6qy2Duvn97yXEKQNQ=
  file: packages/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
